---
- name: install necessary packages for the tor onion service
  apt:
    package: tor
    state: latest
  notify: restart tor

- name: copy torrc template
  template:
    src: torrc.j2
    dest: "{{ torrc }}"
  notify: restart tor
