---
- name: install necessary packages for the tor onion service
  apt:
    package: "{{ item }}"
    state: latest
  notify: restart tor
  with_items:
    - tor
    - torsocks

- name: create tor hidden service directory
  file:
    path: "{{ tor_hidden_service_dir }}"
    state: directory
    owner: debian-tor
    group: debian-tor
    mode: 02700
  notify: restart tor

- name: copy torrc template
  template:
    src: torrc.j2
    dest: "{{ torrc }}"
  notify: restart tor
