---
- name: install necessary packages for the tor onion service
  apt:
    package: "{{ item }}"
    state: latest
  notify: restart tor
  with_items:
    - tor
    - torsocks

- name: copy torrc template
  template:
    src: torrc.j2
    dest: "{{ torrc }}"
  notify: restart tor
